"use client";
import { useAuth } from "@/hooks/useAuth";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useRouter } from "next/navigation";
import { ToastContainer } from "react-toastify";

import { Header } from "@/components/Header/Header";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   const { user } = useAuth();
   const router = useRouter();

   if (!user) {
      router.push("/auth");
   }

   return (
      <html lang="en">
         <body className={inter.className}>
            {user && <Header />}
            {children}
            <ToastContainer theme="light" />
         </body>
      </html>
   );
}
